import { geistSans, geistMono, roboto } from "@/components/fonts/fonts";

import "./globals.css";

export const metadata = {
  title: "Easy Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
